version: '3.7'

services:
  mysql:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: '${APP_NAME}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-password}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-password}'
    ports:
      - '3306:3306'
    volumes:
      - database_volume:/var/lib/${APP_NAME}/db

  mysql-test:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db-test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-password}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-password}'

    ports:
      - '3307:3306'
    volumes:
      - database_volume_test:/var/lib/${APP_NAME}/db-test

volumes:
  database_volume:
  database_volume_test:
